/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASignumberExpr extends PExpr
{
    private TSub _sub_;
    private PExpr _number_;

    public ASignumberExpr()
    {
        // Constructor
    }

    public ASignumberExpr(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PExpr _number_)
    {
        // Constructor
        setSub(_sub_);

        setNumber(_number_);

    }

    @Override
    public Object clone()
    {
        return new ASignumberExpr(
            cloneNode(this._sub_),
            cloneNode(this._number_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignumberExpr(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PExpr getNumber()
    {
        return this._number_;
    }

    public void setNumber(PExpr node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._number_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._number_ == oldChild)
        {
            setNumber((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
