/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AElementExpr extends PExpr
{
    private TIdentifier _identifier_;
    private PExpr _arrayindex_;

    public AElementExpr()
    {
        // Constructor
    }

    public AElementExpr(
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") PExpr _arrayindex_)
    {
        // Constructor
        setIdentifier(_identifier_);

        setArrayindex(_arrayindex_);

    }

    @Override
    public Object clone()
    {
        return new AElementExpr(
            cloneNode(this._identifier_),
            cloneNode(this._arrayindex_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementExpr(this);
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public PExpr getArrayindex()
    {
        return this._arrayindex_;
    }

    public void setArrayindex(PExpr node)
    {
        if(this._arrayindex_ != null)
        {
            this._arrayindex_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayindex_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identifier_)
            + toString(this._arrayindex_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._arrayindex_ == child)
        {
            this._arrayindex_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._arrayindex_ == oldChild)
        {
            setArrayindex((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
