/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AStrExpr extends PExpr
{
    private TStrVal _strVal_;

    public AStrExpr()
    {
        // Constructor
    }

    public AStrExpr(
        @SuppressWarnings("hiding") TStrVal _strVal_)
    {
        // Constructor
        setStrVal(_strVal_);

    }

    @Override
    public Object clone()
    {
        return new AStrExpr(
            cloneNode(this._strVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStrExpr(this);
    }

    public TStrVal getStrVal()
    {
        return this._strVal_;
    }

    public void setStrVal(TStrVal node)
    {
        if(this._strVal_ != null)
        {
            this._strVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._strVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._strVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._strVal_ == child)
        {
            this._strVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._strVal_ == oldChild)
        {
            setStrVal((TStrVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
