/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class AFloatExpr extends PExpr
{
    private TFloatVal _floatVal_;

    public AFloatExpr()
    {
        // Constructor
    }

    public AFloatExpr(
        @SuppressWarnings("hiding") TFloatVal _floatVal_)
    {
        // Constructor
        setFloatVal(_floatVal_);

    }

    @Override
    public Object clone()
    {
        return new AFloatExpr(
            cloneNode(this._floatVal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFloatExpr(this);
    }

    public TFloatVal getFloatVal()
    {
        return this._floatVal_;
    }

    public void setFloatVal(TFloatVal node)
    {
        if(this._floatVal_ != null)
        {
            this._floatVal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._floatVal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._floatVal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._floatVal_ == child)
        {
            this._floatVal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._floatVal_ == oldChild)
        {
            setFloatVal((TFloatVal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
