/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class ASignameExpr extends PExpr
{
    private TSub _sub_;
    private PExpr _name_;

    public ASignameExpr()
    {
        // Constructor
    }

    public ASignameExpr(
        @SuppressWarnings("hiding") TSub _sub_,
        @SuppressWarnings("hiding") PExpr _name_)
    {
        // Constructor
        setSub(_sub_);

        setName(_name_);

    }

    @Override
    public Object clone()
    {
        return new ASignameExpr(
            cloneNode(this._sub_),
            cloneNode(this._name_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignameExpr(this);
    }

    public TSub getSub()
    {
        return this._sub_;
    }

    public void setSub(TSub node)
    {
        if(this._sub_ != null)
        {
            this._sub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sub_ = node;
    }

    public PExpr getName()
    {
        return this._name_;
    }

    public void setName(PExpr node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sub_)
            + toString(this._name_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sub_ == child)
        {
            this._sub_ = null;
            return;
        }

        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sub_ == oldChild)
        {
            setSub((TSub) newChild);
            return;
        }

        if(this._name_ == oldChild)
        {
            setName((PExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
